---
exclude: 'docs'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-vet-repo-mod
        name: go-vet
      - id: go-mod-tidy-repo
        name: go-mod-tidy
- repo: https://github.com/golangci/golangci-lint
  rev: v1.51.2
  hooks:
  - id: golangci-lint
    name: golangci-lint
- repo: https://github.com/Riverside-Healthcare/djlint
  rev: v1.19.15
  hooks:
  - id: djlint-golang
    args: [--reformat]
    types_or: [html]
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.0.0a4
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, "sqlite", --exclude-rules, "L001,L003,L016,L029,L057,L059"]
    - id: sqlfluff-fix
      args: [--dialect, "sqlite", --exclude-rules, "L001,L003,L016,L029,L057,L059"]
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--py310-plus]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=80]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies: [types-all,]
- repo: local
  hooks:
    - id: go-fmt
      name: go-fmt
      description: Runs `gofmt` on Go files
      language: system
      entry: gofmt -w
      types: [go]
    - id: goimports
      name: goimports
      description: Reorganise import statements
      language: system
      entry: goimports -l -w
      types: [go]
-   repo: https://github.com/sco1/brie-commit
    rev: v1.1.0
    hooks:
    -   id: brie-commit
